#!/bin/bash

DENSITY_WWW=/srv/density/www

echo   "=================================="
echo   "Deployment Starting"
echo   "----------------------------------"
echo   "Progress:"
printf "Deploying density.adicu.com          "

GIT_WORK_TREE=$DENSITY_WWW git checkout -f
cd "$DENSITY_WWW"

docker build -t density .
docker kill density
docker rm density
docker run \
    --net=host \
    --restart=always \
    -v $DENSITY_WWW/../logs:/opt/logs \
    -d --name="density" density

printf "Done\n"
exit

