#!/bin/bash

ADI_WWW=/srv/adi-website/www

echo   "=================================="
echo   "Deployment Starting"
echo   "----------------------------------"
echo   "Progress:"
printf "Deploying adicu.com          "

GIT_WORK_TREE=$ADI_WWW git checkout -f
cd "$ADI_WWW"

docker build -t adi-website .
docker kill adi-website
docker rm adi-website

docker run \
    --net=host \
    --restart=always \
    -v $ADI_WWW/../logs:/deploy/logs \
    -v $ADI_WWW/app/static/img/uploaded:/deploy/app/static/img/uploaded \
    -d --name="adi-website" adi-website

printf "Done\n"
exit
